// Hand-authored cinematic seed stories: The Thirsty Crow in English and Hindi.
// Published immediately (manual content skips review) so the app's story
// player has real content before any AI generation runs. The scene JSON
// matches src/services/cinematic.schema.ts exactly — if you edit the shapes
// here, run the schema tests (tests/cinematic.schema.test.ts) to re-verify.

export const cinematicSeedStories = [
  {
    slug: 'thirsty-crow-en',
    title: 'The Thirsty Crow',
    lang: 'en',
    ageBand: 'junior',
    category: 'Moral Stories',
    coverEmoji: '🐦‍⬛',
    music: 'forest',
    moral: 'Where there is a will, there is a way.',
    reward: { stars: 10, coins: 5, badgeStickerId: 'star' },
    scenes: [
      {
        id: 1,
        title: 'A Hot Day',
        minDuration: 8,
        background: 'hot_day',
        narration: 'One day the sun was shining very, very hot. A little crow flew across the sky, looking for water.',
        camera: { effect: 'zoom_in' },
        props: [{ id: 'sun', kind: 'sun', x: 0.78, y: 0.16, scale: 1.2 }],
        characters: [{ id: 'crow', kind: 'crow', x: 0.35, y: 0.45, scale: 1, animation: 'fly' }],
        particles: ['sun_rays', 'wind'],
        interaction: {
          type: 'tap',
          target: 'sun',
          hint: 'Touch the hot sun!',
          sound: 'chime',
        },
      },
      {
        id: 2,
        title: 'Looking for Water',
        minDuration: 8,
        background: 'village',
        narration: 'The crow was so thirsty. He looked here and he looked there, but he could not find any water.',
        camera: { effect: 'pan_right' },
        props: [
          { id: 'house', kind: 'house', x: 0.2, y: 0.68, scale: 1 },
          { id: 'tree', kind: 'tree', x: 0.82, y: 0.6, scale: 1.1 },
        ],
        characters: [{ id: 'crow', kind: 'crow', x: 0.5, y: 0.42, scale: 1, animation: 'fly' }],
        particles: ['wind'],
        interaction: null,
      },
      {
        id: 3,
        title: 'The Pot',
        minDuration: 8,
        background: 'village',
        narration: 'Then he saw a pot under a tree! Can you help the crow fly to the pot?',
        camera: { effect: 'zoom_in' },
        props: [
          { id: 'tree', kind: 'tree', x: 0.75, y: 0.55, scale: 1.2 },
          { id: 'pot', kind: 'pot', x: 0.6, y: 0.78, scale: 1 },
        ],
        characters: [{ id: 'crow', kind: 'crow', x: 0.2, y: 0.4, scale: 1, animation: 'idle' }],
        particles: ['birds'],
        interaction: {
          type: 'drag',
          target: 'crow',
          dropZone: 'pot',
          hint: 'Take the crow to the pot!',
          sound: 'plop',
        },
      },
      {
        id: 4,
        title: 'Clever Pebbles',
        minDuration: 9,
        background: 'village',
        narration: 'The water was too low to reach. So the clever crow dropped little pebbles into the pot, one by one, and the water rose up and up!',
        camera: { effect: 'none' },
        props: [
          { id: 'pot', kind: 'pot', x: 0.5, y: 0.72, scale: 1.3 },
          { id: 'rock', kind: 'rock', x: 0.25, y: 0.82, scale: 0.8 },
        ],
        characters: [{ id: 'crow', kind: 'crow', x: 0.5, y: 0.45, scale: 1, animation: 'bounce' }],
        particles: ['bubbles'],
        interaction: null,
      },
      {
        id: 5,
        title: 'A Happy Ending',
        minDuration: 8,
        background: 'sky',
        narration: 'The crow drank the cool water and flew away happy. When something is hard, think and try — where there is a will, there is a way!',
        camera: { effect: 'zoom_out' },
        props: [
          { id: 'sun', kind: 'sun', x: 0.8, y: 0.15, scale: 1 },
          { id: 'cloud', kind: 'cloud', x: 0.25, y: 0.2, scale: 1 },
        ],
        characters: [{ id: 'crow', kind: 'crow', x: 0.5, y: 0.4, scale: 1.1, animation: 'fly' }],
        particles: ['birds', 'wind'],
        interaction: null,
      },
    ],
  },
  {
    slug: 'thirsty-crow-hi',
    title: 'प्यासा कौआ',
    lang: 'hi',
    ageBand: 'junior',
    category: 'Moral Stories',
    coverEmoji: '🐦‍⬛',
    music: 'forest',
    moral: 'जहाँ चाह, वहाँ राह।',
    reward: { stars: 10, coins: 5, badgeStickerId: 'star' },
    scenes: [
      {
        id: 1,
        title: 'गर्मी का दिन',
        minDuration: 8,
        background: 'hot_day',
        narration: 'एक दिन बहुत तेज़ गर्मी थी। एक छोटा कौआ पानी की तलाश में आसमान में उड़ रहा था।',
        camera: { effect: 'zoom_in' },
        props: [{ id: 'sun', kind: 'sun', x: 0.78, y: 0.16, scale: 1.2 }],
        characters: [{ id: 'crow', kind: 'crow', x: 0.35, y: 0.45, scale: 1, animation: 'fly' }],
        particles: ['sun_rays', 'wind'],
        interaction: {
          type: 'tap',
          target: 'sun',
          hint: 'सूरज को छुओ!',
          sound: 'chime',
        },
      },
      {
        id: 2,
        title: 'पानी की तलाश',
        minDuration: 8,
        background: 'village',
        narration: 'कौआ बहुत प्यासा था। उसने यहाँ देखा, वहाँ देखा, पर कहीं पानी नहीं मिला।',
        camera: { effect: 'pan_right' },
        props: [
          { id: 'house', kind: 'house', x: 0.2, y: 0.68, scale: 1 },
          { id: 'tree', kind: 'tree', x: 0.82, y: 0.6, scale: 1.1 },
        ],
        characters: [{ id: 'crow', kind: 'crow', x: 0.5, y: 0.42, scale: 1, animation: 'fly' }],
        particles: ['wind'],
        interaction: null,
      },
      {
        id: 3,
        title: 'घड़ा मिला',
        minDuration: 8,
        background: 'village',
        narration: 'तभी उसे पेड़ के नीचे एक घड़ा दिखा! क्या तुम कौए को घड़े तक पहुँचा सकते हो?',
        camera: { effect: 'zoom_in' },
        props: [
          { id: 'tree', kind: 'tree', x: 0.75, y: 0.55, scale: 1.2 },
          { id: 'pot', kind: 'pot', x: 0.6, y: 0.78, scale: 1 },
        ],
        characters: [{ id: 'crow', kind: 'crow', x: 0.2, y: 0.4, scale: 1, animation: 'idle' }],
        particles: ['birds'],
        interaction: {
          type: 'drag',
          target: 'crow',
          dropZone: 'pot',
          hint: 'कौए को घड़े तक ले जाओ!',
          sound: 'plop',
        },
      },
      {
        id: 4,
        title: 'चतुर कौआ',
        minDuration: 9,
        background: 'village',
        narration: 'पानी बहुत नीचे था। चतुर कौए ने एक-एक करके छोटे कंकड़ घड़े में डाले, और पानी ऊपर आता गया!',
        camera: { effect: 'none' },
        props: [
          { id: 'pot', kind: 'pot', x: 0.5, y: 0.72, scale: 1.3 },
          { id: 'rock', kind: 'rock', x: 0.25, y: 0.82, scale: 0.8 },
        ],
        characters: [{ id: 'crow', kind: 'crow', x: 0.5, y: 0.45, scale: 1, animation: 'bounce' }],
        particles: ['bubbles'],
        interaction: null,
      },
      {
        id: 5,
        title: 'खुशी की उड़ान',
        minDuration: 8,
        background: 'sky',
        narration: 'कौए ने ठंडा पानी पिया और खुशी-खुशी उड़ गया। जब कोई काम मुश्किल लगे, तो सोचो और कोशिश करो — जहाँ चाह, वहाँ राह!',
        camera: { effect: 'zoom_out' },
        props: [
          { id: 'sun', kind: 'sun', x: 0.8, y: 0.15, scale: 1 },
          { id: 'cloud', kind: 'cloud', x: 0.25, y: 0.2, scale: 1 },
        ],
        characters: [{ id: 'crow', kind: 'crow', x: 0.5, y: 0.4, scale: 1.1, animation: 'fly' }],
        particles: ['birds', 'wind'],
        interaction: null,
      },
    ],
  },
];
